In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import tree
from sklearn.neighbors import KNeighborsClassifier

In [35]:
iris=load_iris()
train_data,test_data,train_target,test_target=train_test_split(iris.data,iris.target,test_size=0.1)
clf=tree.DecisionTreeClassifier()
trained=clf.fit(train_data,train_target)
output=trained.predict(test_data)
print(test_target)
print(output)
print(accuracy_score(test_target,output))
knnclf=KNeighborsClassifier(n_neighbors=5)
trainedknn=knnclf.fit(train_data,train_target)
out=trainedknn.predict(test_data)
print(out)
print(accuracy_score(test_target,output))

[1 2 2 1 2 0 0 2 1 2 1 0 1 2 2]
[1 2 1 1 2 0 0 2 1 2 1 0 1 2 2]
0.9333333333333333
[1 1 1 1 1 0 0 1 1 1 1 0 1 1 1]
0.9333333333333333


In [39]:
tree.export_graphviz(clf, out_file="tree.dot", max_depth=7, feature_names=iris.feature_names, class_names=iris.target_names, filled=True, rounded=True)

In [38]:

print(type(iris.target_names))

<class 'numpy.ndarray'>
